"""Deterministic synthesis of the CC0 clips we generate ourselves (no fetch): the
nursery noise floor and the white-noise / lullaby confuser sources.

Byte-identical for a given seed (numpy PCG64 + libsndfile PCM_16), so each generated
clip has a stable SHA-256 pinned in the manifest — the build regenerates and
re-verifies it, catching any drift in this generator (bump the seed/version if the
output must change).
"""

from __future__ import annotations

import contextlib
import hashlib
import io
import os
import tempfile
from pathlib import Path

import numpy as np
import soundfile as sf

from eeper_fixtures.manifest import Gen

SR = 16000


def _to_wav_bytes(samples: np.ndarray) -> bytes:
    buf = io.BytesIO()
    sf.write(
        buf, np.clip(samples, -1.0, 1.0).astype(np.float32), SR, format="WAV", subtype="PCM_16"
    )
    return buf.getvalue()


def _white_noise(rng: np.random.Generator, n: int, level: float) -> np.ndarray:
    return level * rng.standard_normal(n)


def _lullaby(rng: np.random.Generator, n: int, level: float) -> np.ndarray:
    # A simple music-box-ish pentatonic melody of decaying sine tones — reads as
    # "music", never "cry", to YAMNet.
    scale = np.array([261.63, 293.66, 329.63, 392.0, 440.0])  # C D E G A
    note_len = int(SR * 0.4)
    t = np.arange(note_len) / SR
    envelope = np.exp(-4.0 * t / (note_len / SR))
    out = np.zeros(n, dtype=np.float64)
    pos = 0
    while pos < n:
        freq = float(scale[rng.integers(len(scale))])
        tone = level * np.sin(2.0 * np.pi * freq * t) * envelope
        end = min(pos + note_len, n)
        out[pos:end] += tone[: end - pos]
        pos += note_len
    return out


def _nursery_floor(rng: np.random.Generator, n: int, level: float) -> np.ndarray:
    # A quiet broadband bed for scene backgrounds.
    return level * rng.standard_normal(n)


_GENERATORS = {
    "white_noise": _white_noise,
    "lullaby": _lullaby,
    "nursery_floor": _nursery_floor,
}


def generate_clip(gen: Gen) -> bytes:
    generator = _GENERATORS.get(gen.kind)
    if generator is None:
        raise ValueError(f"unknown gen kind {gen.kind!r}")
    rng = np.random.default_rng(gen.seed)
    return _to_wav_bytes(generator(rng, int(SR * gen.duration), gen.level))


def generated_sha256(gen: Gen) -> str:
    """The pinnable SHA-256 of a generated clip (used when writing the manifest)."""
    return hashlib.sha256(generate_clip(gen)).hexdigest()


def ensure_generated(clip_id: str, gen: Gen, expected_sha256: str, cache_dir: Path) -> Path:
    """Regenerate a clip into the cache and verify it matches the pinned SHA-256
    (drift guard). Raises ValueError on mismatch."""
    data = generate_clip(gen)
    actual = hashlib.sha256(data).hexdigest()
    if actual != expected_sha256:
        raise ValueError(
            f"{clip_id}: generated bytes drifted (expected {expected_sha256}, got {actual})"
        )
    target = cache_dir / "clips" / f"{clip_id}.wav"
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=target.parent, suffix=".part")
    try:
        with os.fdopen(fd, "wb") as out:
            out.write(data)
        os.replace(tmp, target)
    finally:
        with contextlib.suppress(FileNotFoundError):
            os.unlink(tmp)
    return target
